version: '3'

services:
  db:
    image: postgres:latest
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  #start gunicorn in dockerfile and take away ports in web service
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/aioblog
    ports:
      - "8080:8080"
    depends_on:
      - db
    tty: true

volumes:
  database-data: